export const DEFAULT_ITEM = [
  {
    id:1,
  category:"Fruits and Vegetables",
  item_name:"Apple",
  image:"/images/img1.webp",
 current_price:65,
 original_price:80,
},
{
  id:2,
category:"Fruits and Vegetables",
  item_name:"Pineapple",
  image:"/images/img2.webp",
  current_price:70,
  original_price:85,
},
{
  id:3,
category:"Fruits and Vegetables",
item_name:"Mango",
image:"/images/img3.jpg",
current_price:120,
 original_price:145,
},{
  id:4,
 category:"Fruits and Vegetables",
 item_name:"Strawbery",
 image:"/images/img4.jpg",
 current_price:120,
 original_price:150,
},{
  id:5,
 category:"Fruits and Vegetables",
 item_name:"Lychee",
 image:"/images/img5.jpg",
 current_price:50,
 original_price:55,
},
{
  id:6,
 category:"Fruits and Vegetables",
 item_name:"Papaya",
 image:"/images/img6.jpg",
 current_price:40,
 original_price:54,
},{
  id:7,
 category:"Fruits and Vegetables",
 item_name:"Dragon Fruit",
 image:"/images/img7.webp",
 current_price:150,
 original_price:175,
},{
  id:8,
 category:"Fruits and Vegetables",
 item_name:"Banana",
 image:"/images/img8.jpg",
 current_price:55,
 original_price:65,
},{
  id:9,
  category:"Grocery",
  item_name:"Milk",
  image:"/images/img9.webp",
  current_price:28,
  original_price:33,
},
{
id:10,
category:"Grocery",
  item_name:"Butter",
  image:"/images/img10.jpg",
  current_price:75,
  original_price:90,
},
{
id:11,
category:"Grocery",
item_name:"Ice-cream",
image:"/images/img11.jpg",
current_price:190,
original_price:220,
},{
id:12,
 category:"Grocery",
 item_name:"Bread",
 image:"/images/img12.jpg",
 current_price:40,
 original_price:50,
},{
id:13,
 category:"Grocery",
 item_name:"Surf Excel",
 image:"/images/img13.jpg",
 current_price:40,
 original_price:45,
},
{
id:14,
 
 category:"Grocery",
 item_name:"Harpic",
 image:"/images/img14.jpg",
 current_price:170,
 original_price:190,
},{
id:15,
 category:"Grocery",
 item_name:"Corn Flakes",
 image:"/images/img15.jpg",
 current_price:100,
 original_price:120,
},{
id:16,
 category:"Grocery",
 item_name:"Lays",
 image:"/images/img16.jpg",
 current_price:25,
 original_price:25,
},
];